common:
    # lid_topic:  "/velodyne_points"
#    imu_topic:  "/kitti/oxts/imu/extract"
    lid_topic:  "/hesai/pandar"
    imu_topic:  "/imu/raw"
    time_sync_en: true         # ONLY turn on when external time synchronization is really not possible
    time_offset_lidar_to_imu: 0 # Time offset between lidar and IMU calibrated by other algorithms, e.g. LI-Init (can be found in README).
                                  # This param will take effect no matter what time_sync_en is. So if the time offset is not known exactly, please set as 0.0

preprocess:
    lidar_type: 2                # 1 for Livox serials LiDAR, 2 for Velodyne LiDAR, 3 for ouster LiDAR, 
    scan_line: 64
    scan_rate: 10                # only need to be set for velodyne, unit: Hz,
    timestamp_unit: 2            # the unit of time/t field in the PointCloud2 rostopic: 0-second, 1-milisecond, 2-microsecond, 3-nanosecond.
    blind: 0.5
    point_filter_num: 1

mapping:
    acc_cov: 0.01
    gyr_cov: 0.01
    b_acc_cov: 0.0001
    b_gyr_cov: 0.0001
    fov_degree:    180
    det_range:     100.0
    extrinsic_est_en:  false      # true: enable the online estimation of IMU-LiDAR extrinsic,
    # extrinsic_T: [ 0, 0, 0.07]
    # extrinsic_R: [ 0, -1, 0, 
    #                1, 0, 0, 
    #                0, 0, 1]
    # extrinsic_T: [0.0141813, 0.465524, -0.132476]
    # extrinsic_R:  [ -0.595102, 0.795018, -0.117469,  -0.792086, -0.604947, -0.0814795, -0.13584, 0.0445566, 0.989728]
    # extrinsic_T: [0.085, 0.091, 0.017]
    # extrinsic_R:  [0.170911, 0.984979, 0.0245961, -0.984498, 0.17172, -0.0357161, -0.0394032, -0.0181105,  0.999059]
    extrinsic_T: [0.0, 0.05, 0.13]
    # extrinsic_R:  [0.170911, 0.984979, 0.0245961, -0.984498, 0.17172, -0.0357161, -0.0394032, -0.0181105,  0.999059]
    extrinsic_R:  [1, 0, 0, 0, 1, 0, 0, 0,  1]



publish:
    path_en:  false
    scan_publish_en:  true       # false: close all the point cloud output
    dense_publish_en: true       # false: low down the points number in a global-frame point clouds scan.
    scan_bodyframe_pub_en: true  # true: output the point cloud scans in IMU-body-frame

pcd_save:
    pcd_save_en: true
    interval: -1                 # how many LiDAR frames saved in each pcd file; 
                                 # -1 : all frames will be saved in ONE pcd file, may lead to memory crash when having too much frames.
